#!/usr/bin/env python3

import subprocess
import sys

if b"master_WIP" in subprocess.check_output(["git","rev-parse","--abbrev-ref", "HEAD"]):
	try:
		subprocess.check_call(["make", "test"])
	except subprocess.CalledProcessError:
		print("Tests failed. Cancelling push.")
		sys.exit(1)

	try:
		subprocess.check_call(["make", "doc"])
	except subprocess.CalledProcessError:
		print("Doc generation failed.")
